version: '3'
services:

  flask:
    build:
      context: ./
    container_name: 'flask'
    tty: true
    ports:
      - 8050:8050
    volumes:
      - ./src/:/workspace/src/
      - ./static/:/workspace/static/
      - ./templates/:/workspace/templates/
      - ./app.py:/workspace/app.py
    working_dir: /workspace
    command: python app.py
